name: alarmapp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  alarm: ^3.1.5
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
 